version: 0.2
        
phases:
  install:
    runtime-versions:
      #java: openjdk8  // Error en AWS (YAML_FILE_ERROR: Unknown runtime version named 'openjdk8' of java. This build image has the following versions: corretto11, corretto8)
      java: corretto8
    commands:
      - echo install
    #finally:
     # - command. // Comando se ejecuta en un "Finalñy"
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/spring-boot-todo-rest-api-h2-aws-pipeline-0.0.1-SNAPSHOT.jar
